/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.SessionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SessionsApi', function() {
    describe('deleteSessionSessionsDeletePost', function() {
      it('should call deleteSessionSessionsDeletePost successfully', function(done) {
        //uncomment below and update the code to test deleteSessionSessionsDeletePost
        //instance.deleteSessionSessionsDeletePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMessagesSessionsMessagesGet', function() {
      it('should call getMessagesSessionsMessagesGet successfully', function(done) {
        //uncomment below and update the code to test getMessagesSessionsMessagesGet
        //instance.getMessagesSessionsMessagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSessionsSessionsPost', function() {
      it('should call getSessionsSessionsPost successfully', function(done) {
        //uncomment below and update the code to test getSessionsSessionsPost
        //instance.getSessionsSessionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('insertSessionSessionsInsertPost', function() {
      it('should call insertSessionSessionsInsertPost successfully', function(done) {
        //uncomment below and update the code to test insertSessionSessionsInsertPost
        //instance.insertSessionSessionsInsertPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('runCrewSessionsRunPost', function() {
      it('should call runCrewSessionsRunPost successfully', function(done) {
        //uncomment below and update the code to test runCrewSessionsRunPost
        //instance.runCrewSessionsRunPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSessionSessionsUpdatePost', function() {
      it('should call updateSessionSessionsUpdatePost successfully', function(done) {
        //uncomment below and update the code to test updateSessionSessionsUpdatePost
        //instance.updateSessionSessionsUpdatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('upsertSessionSessionsUpsertPost', function() {
      it('should call upsertSessionSessionsUpsertPost successfully', function(done) {
        //uncomment below and update the code to test upsertSessionSessionsUpsertPost
        //instance.upsertSessionSessionsUpsertPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
