/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/sessions/": {
    /** Get Sessions */
    get: operations["get_sessions_sessions__get"];
    /** Insert Session */
    post: operations["insert_session_sessions__post"];
  };
  "/sessions/{session_id}": {
    /** Get Session */
    get: operations["get_session_sessions__session_id__get"];
    /** Delete Session */
    delete: operations["delete_session_sessions__session_id__delete"];
    /** Update Session */
    patch: operations["update_session_sessions__session_id__patch"];
  };
  "/sessions/run": {
    /** Run Crew */
    post: operations["run_crew_sessions_run_post"];
  };
  "/messages/": {
    /** Get Messages */
    get: operations["get_messages_messages__get"];
    /** Insert Message */
    post: operations["insert_message_messages__post"];
  };
  "/messages/{message_id}": {
    /** Get Message */
    get: operations["get_message_messages__message_id__get"];
    /** Delete Message */
    delete: operations["delete_message_messages__message_id__delete"];
    /** Update Message */
    patch: operations["update_message_messages__message_id__patch"];
  };
  "/crews/": {
    /** Get Crews */
    get: operations["get_crews_crews__get"];
    /** Insert Crew */
    post: operations["insert_crew_crews__post"];
  };
  "/crews/{crew_id}": {
    /** Get Crew By Id */
    get: operations["get_crew_by_id_crews__crew_id__get"];
    /** Delete Crew */
    delete: operations["delete_crew_crews__crew_id__delete"];
    /** Update Crew */
    patch: operations["update_crew_crews__crew_id__patch"];
  };
  "/agents/": {
    /** Get Agents */
    get: operations["get_agents_agents__get"];
    /** Insert Agent */
    post: operations["insert_agent_agents__post"];
  };
  "/agents/{agent_id}": {
    /** Get Agent By Id */
    get: operations["get_agent_by_id_agents__agent_id__get"];
    /** Delete Agent */
    delete: operations["delete_agent_agents__agent_id__delete"];
    /** Patch Agent */
    patch: operations["patch_agent_agents__agent_id__patch"];
  };
  "/profiles/": {
    /** Get Profiles */
    get: operations["get_profiles_profiles__get"];
    /** Insert Profile */
    post: operations["insert_profile_profiles__post"];
  };
  "/profiles/{profile_id}": {
    /** Get Profile By Id */
    get: operations["get_profile_by_id_profiles__profile_id__get"];
    /** Delete Profile */
    delete: operations["delete_profile_profiles__profile_id__delete"];
    /** Update Profile */
    patch: operations["update_profile_profiles__profile_id__patch"];
  };
  "/profiles/{profile_id}/api_keys": {
    /**
     * Get Api Keys
     * @description Returns api keys with the api key type as an object with the id, name, description etc.
     */
    get: operations["get_api_keys_profiles__profile_id__api_keys_get"];
  };
  "/profiles/api_keys": {
    /** Insert Api Key */
    post: operations["insert_api_key_profiles_api_keys_post"];
  };
  "/profiles/api_keys/{api_key_id}": {
    /** Delete Api Key */
    delete: operations["delete_api_key_profiles_api_keys__api_key_id__delete"];
    /** Update Api Key */
    patch: operations["update_api_key_profiles_api_keys__api_key_id__patch"];
  };
  "/auth/sign_in/provider": {
    /** Provider Sign In */
    post: operations["provider_sign_in_auth_sign_in_provider_post"];
  };
  "/api_key_types/": {
    /** Get All Api Key Types */
    get: operations["get_all_api_key_types_api_key_types__get"];
  };
  "/rest/": {
    /** Redirect To Docs */
    get: operations["redirect_to_docs_rest__get"];
  };
  "/rest/test": {
    /** Test */
    get: operations["test_rest_test_get"];
  };
  "/rest/stop/{worker_id}": {
    /** Stop Stream */
    post: operations["stop_stream_rest_stop__worker_id__post"];
  };
  "/rest/generate-comment": {
    /** Generate Comment */
    post: operations["generate_comment_rest_generate_comment_post"];
  };
  "/rest/mark-lead-as-irrelevant": {
    /** Mark Lead As Irrelevant */
    post: operations["mark_lead_as_irrelevant_rest_mark_lead_as_irrelevant_post"];
  };
  "/rest/publish-comment": {
    /** Publish Comment */
    post: operations["publish_comment_rest_publish_comment_post"];
  };
  "/": {
    /** Redirect To Docs */
    get: operations["redirect_to_docs__get"];
  };
  "/compile": {
    /** Compile */
    get: operations["compile_compile_get"];
  };
  "/improve": {
    /** Improve */
    get: operations["improve_improve_get"];
  };
  "/auto-build": {
    /** Auto Build Crew */
    get: operations["auto_build_crew_auto_build_get"];
  };
  "/me": {
    /** Get Profile From Header */
    get: operations["get_profile_from_header_me_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** APIKey */
    APIKey: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      api_key_type?: components["schemas"]["APIKeyType"] | null;
      /** Api Key */
      api_key: string;
    };
    /** APIKeyInsertRequest */
    APIKeyInsertRequest: {
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /**
       * Api Key Type Id
       * Format: uuid
       */
      api_key_type_id: string;
      /** Api Key */
      api_key: string;
    };
    /** APIKeyType */
    APIKeyType: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
    };
    /** APIKeyUpdateRequest */
    APIKeyUpdateRequest: {
      /** Api Key */
      api_key: string;
    };
    /** Agent */
    Agent: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Title */
      title: string;
      /** Published */
      published: boolean;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /** Avatar */
      avatar: string;
      /** System Message */
      system_message: string;
      /**
       * Model
       * @enum {string}
       */
      model: "gpt-3.5-turbo" | "gpt-4-turbo-preview";
      /** Tools */
      tools: Record<string, never>[];
      /** Description */
      description?: string | null;
      /** Role */
      role: string;
      /** Version */
      version?: string | null;
    };
    /** AgentInsertRequest */
    AgentInsertRequest: {
      /** Title */
      title: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /** Avatar */
      avatar: string;
      /** System Message */
      system_message: string;
      /**
       * Model
       * @enum {string}
       */
      model: "gpt-3.5-turbo" | "gpt-4-turbo-preview";
      /** Tools */
      tools: Record<string, never>[];
      /** Description */
      description?: string | null;
      /** Role */
      role: string;
      /** Version */
      version?: string | null;
    };
    /** AgentUpdateModel */
    AgentUpdateModel: {
      /** Title */
      title?: string | null;
      /** Published */
      published?: boolean | null;
      /** Profile Id */
      profile_id?: string | null;
      /** Avatar */
      avatar?: string | null;
      /** System Message */
      system_message?: string | null;
      /** Model */
      model?: ("gpt-3.5-turbo" | "gpt-4-turbo-preview") | null;
      /** Tools */
      tools?: Record<string, never>[] | null;
      /** Version */
      version?: string | null;
      /** Description */
      description?: string | null;
      /** Role */
      role?: string | null;
    };
    /** Crew */
    Crew: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /** Edges */
      edges: Record<string, never>[];
      /** Published */
      published: boolean;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Nodes */
      nodes: string[];
      /** Receiver Id */
      receiver_id?: string | null;
      /** Avatar */
      avatar?: string | null;
      /** Prompt */
      prompt?: Record<string, never> | null;
    };
    /** CrewInsertRequest */
    CrewInsertRequest: {
      /**
       * Receiver Id
       * Format: uuid
       */
      receiver_id: string;
      /** Prompt */
      prompt: Record<string, never>;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /** Edges */
      edges: Record<string, never>[];
      /** Published */
      published: boolean;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Nodes */
      nodes: string[];
    };
    /** CrewProcessed */
    CrewProcessed: {
      /**
       * Receiver Id
       * Format: uuid
       */
      receiver_id: string;
      /** Delegator Id */
      delegator_id?: string | null;
      /** Agents */
      agents: components["schemas"]["Agent"][];
      /**
       * Sub Crews
       * @default []
       */
      sub_crews?: components["schemas"]["Crew"][];
    };
    /** CrewUpdateRequest */
    CrewUpdateRequest: {
      /** Receiver Id */
      receiver_id?: string | null;
      /** Prompt */
      prompt?: Record<string, never> | null;
      /** Profile Id */
      profile_id?: string | null;
      /** Edges */
      edges?: Record<string, never>[] | null;
      /** Published */
      published?: boolean | null;
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Nodes */
      nodes?: string[] | null;
    };
    /** FalseLead */
    FalseLead: {
      /**
       * Lead Id
       * Format: uuid
       */
      lead_id: string;
      /**
       * Submission Id
       * Format: uuid
       */
      submission_id: string;
      /** Correct Reason */
      correct_reason: string;
    };
    /** GenerateCommentRequest */
    GenerateCommentRequest: {
      /** Title */
      title: string;
      /** Selftext */
      selftext: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Message */
    Message: {
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /** Sender Id */
      sender_id?: string | null;
      /** Recipient Id */
      recipient_id?: string | null;
      /** Content */
      content: string;
      /**
       * Role
       * @default user
       */
      role?: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
    };
    /** MessageInsertRequest */
    MessageInsertRequest: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Content */
      content: string;
      /**
       * Role
       * @default user
       */
      role?: string;
      /** Recipient Id */
      recipient_id?: string | null;
      /** Sender Id */
      sender_id?: string | null;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
    };
    /** MessageUpdateRequest */
    MessageUpdateRequest: {
      /** Session Id */
      session_id?: string | null;
      /** Content */
      content?: string | null;
      /** Role */
      role?: string | null;
      /** Recipient Id */
      recipient_id?: string | null;
      /** Sender Id */
      sender_id?: string | null;
      /** Profile Id */
      profile_id?: string | null;
    };
    /** OAuthResponse */
    OAuthResponse: {
      /**
       * Provider
       * @enum {string}
       */
      provider: "apple" | "azure" | "bitbucket" | "discord" | "facebook" | "figma" | "github" | "gitlab" | "google" | "kakao" | "keycloak" | "linkedin" | "notion" | "slack" | "spotify" | "twitch" | "twitter" | "workos" | "zoom";
      /** Url */
      url: string;
    };
    /** Profile */
    Profile: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Tier Id
       * Format: uuid
       */
      tier_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Display Name */
      display_name: string;
      /** Stripe Customer Id */
      stripe_customer_id: string | null;
    };
    /** ProfileInsertRequest */
    ProfileInsertRequest: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Tier Id
       * Format: uuid
       */
      tier_id: string;
      /** Display Name */
      display_name: string;
      /** Stripe Customer Id */
      stripe_customer_id?: string | null;
    };
    /** ProfileUpdateRequest */
    ProfileUpdateRequest: {
      /** Tier Id */
      tier_id?: string | null;
      /** Display Name */
      display_name?: string | null;
      /** Stripe Customer Id */
      stripe_customer_id?: string | null;
    };
    /** PublishCommentRequest */
    PublishCommentRequest: {
      /**
       * Lead Id
       * Format: uuid
       */
      lead_id: string;
      /** Comment */
      comment: string;
      /** Reddit Username */
      reddit_username: string;
      /** Reddit Password */
      reddit_password: string;
    };
    /** Session */
    Session: {
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /**
       * Reply
       * @default
       */
      reply?: string;
      /**
       * Crew Id
       * Format: uuid
       */
      crew_id: string;
      /**
       * Title
       * @default Untitled
       */
      title?: string;
      /**
       * Last Opened At
       * Format: date-time
       */
      last_opened_at?: string;
      /** @default running */
      status?: components["schemas"]["SessionStatus"];
    };
    /** SessionInsertRequest */
    SessionInsertRequest: {
      /**
       * Crew Id
       * Format: uuid
       */
      crew_id: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /** Title */
      title: string | null;
    };
    /** SessionRunRequest */
    SessionRunRequest: {
      /**
       * Crew Id
       * Format: uuid
       */
      crew_id: string;
      /**
       * Profile Id
       * Format: uuid
       */
      profile_id: string;
      /**
       * Session Title
       * @default Untitled
       */
      session_title?: string;
      /** Session Id */
      session_id?: string | null;
      /** Reply */
      reply?: string | null;
    };
    /**
     * SessionStatus
     * @enum {string}
     */
    SessionStatus: "running" | "finished" | "idle";
    /** SessionUpdateRequest */
    SessionUpdateRequest: {
      /** Crew Id */
      crew_id?: string | null;
      /** Reply */
      reply?: string | null;
      /** Profile Id */
      profile_id?: string | null;
      /** Title */
      title?: string | null;
      status?: components["schemas"]["SessionStatus"] | null;
    };
    /** SignInWithOAuthCredentials */
    SignInWithOAuthCredentials: {
      /**
       * Provider
       * @enum {string}
       */
      provider: "apple" | "azure" | "bitbucket" | "discord" | "facebook" | "figma" | "github" | "gitlab" | "google" | "kakao" | "keycloak" | "linkedin" | "notion" | "slack" | "spotify" | "twitch" | "twitter" | "workos" | "zoom";
      options?: components["schemas"]["SignInWithOAuthCredentialsOptions"];
    };
    /** SignInWithOAuthCredentialsOptions */
    SignInWithOAuthCredentialsOptions: {
      /** Redirect To */
      redirect_to?: string;
      /** Scopes */
      scopes?: string;
      /** Query Params */
      query_params?: {
        [key: string]: string;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Sessions */
  get_sessions_sessions__get: {
    parameters: {
      query?: {
        profile_id?: string | null;
        crew_id?: string | null;
        title?: string | null;
        status?: components["schemas"]["SessionStatus"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Session */
  insert_session_sessions__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionInsertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Session */
  get_session_sessions__session_id__get: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Session */
  delete_session_sessions__session_id__delete: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Session */
  update_session_sessions__session_id__patch: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Run Crew */
  run_crew_sessions_run_post: {
    parameters: {
      query?: {
        mock?: boolean;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Messages */
  get_messages_messages__get: {
    parameters: {
      query?: {
        session_id?: string | null;
        profile_id?: string | null;
        recipient_id?: string | null;
        sender_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Message"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Message */
  insert_message_messages__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageInsertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Message */
  get_message_messages__message_id__get: {
    parameters: {
      path: {
        message_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Message */
  delete_message_messages__message_id__delete: {
    parameters: {
      path: {
        message_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Message */
  update_message_messages__message_id__patch: {
    parameters: {
      path: {
        message_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Crews */
  get_crews_crews__get: {
    parameters: {
      query?: {
        profile_id?: string | null;
        receiver_id?: string | null;
        title?: string | null;
        published?: boolean | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Crew"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Crew */
  insert_crew_crews__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CrewInsertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Crew"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Crew By Id */
  get_crew_by_id_crews__crew_id__get: {
    parameters: {
      path: {
        crew_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Crew"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Crew */
  delete_crew_crews__crew_id__delete: {
    parameters: {
      path: {
        crew_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Crew"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Crew */
  update_crew_crews__crew_id__patch: {
    parameters: {
      path: {
        crew_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CrewUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Crew"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Agents */
  get_agents_agents__get: {
    parameters: {
      query?: {
        profile_id?: string | null;
        crew_id?: string | null;
        published?: boolean | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Agent */
  insert_agent_agents__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentInsertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Agent By Id */
  get_agent_by_id_agents__agent_id__get: {
    parameters: {
      path: {
        agent_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Agent */
  delete_agent_agents__agent_id__delete: {
    parameters: {
      path: {
        agent_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Patch Agent */
  patch_agent_agents__agent_id__patch: {
    parameters: {
      path: {
        agent_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentUpdateModel"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Agent"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Profiles */
  get_profiles_profiles__get: {
    parameters: {
      query?: {
        tier_id?: string | null;
        display_name?: string | null;
        stripe_customer_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Profile"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Profile */
  insert_profile_profiles__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileInsertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Profile By Id */
  get_profile_by_id_profiles__profile_id__get: {
    parameters: {
      path: {
        profile_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Profile */
  delete_profile_profiles__profile_id__delete: {
    parameters: {
      path: {
        profile_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Profile */
  update_profile_profiles__profile_id__patch: {
    parameters: {
      path: {
        profile_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Api Keys
   * @description Returns api keys with the api key type as an object with the id, name, description etc.
   */
  get_api_keys_profiles__profile_id__api_keys_get: {
    parameters: {
      path: {
        profile_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKey"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Api Key */
  insert_api_key_profiles_api_keys_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["APIKeyInsertRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["APIKey"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Api Key */
  delete_api_key_profiles_api_keys__api_key_id__delete: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKey"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Api Key */
  update_api_key_profiles_api_keys__api_key_id__patch: {
    parameters: {
      path: {
        api_key_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["APIKeyUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKey"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Provider Sign In */
  provider_sign_in_auth_sign_in_provider_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInWithOAuthCredentials"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OAuthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get All Api Key Types */
  get_all_api_key_types_api_key_types__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["APIKeyType"][];
        };
      };
    };
  };
  /** Redirect To Docs */
  redirect_to_docs_rest__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Test */
  test_rest_test_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Stop Stream */
  stop_stream_rest_stop__worker_id__post: {
    parameters: {
      path: {
        worker_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Generate Comment */
  generate_comment_rest_generate_comment_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateCommentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Mark Lead As Irrelevant */
  mark_lead_as_irrelevant_rest_mark_lead_as_irrelevant_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["FalseLead"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Publish Comment */
  publish_comment_rest_publish_comment_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PublishCommentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Redirect To Docs */
  redirect_to_docs__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Compile */
  compile_compile_get: {
    parameters: {
      query: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string | components["schemas"]["CrewProcessed"];
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Improve */
  improve_improve_get: {
    parameters: {
      query: {
        word_limit: number;
        prompt: string;
        prompt_type: "generic" | "system" | "user";
        temperature: number;
        profile_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Auto Build Crew */
  auto_build_crew_auto_build_get: {
    parameters: {
      query: {
        general_task: string;
        profile_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Profile From Header */
  get_profile_from_header_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
