/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CrewRequestModel from '../model/CrewRequestModel';
import HTTPValidationError from '../model/HTTPValidationError';

/**
* Crews service.
* @module api/CrewsApi
* @version 0.1.0
*/
export default class CrewsApi {

    /**
    * Constructs a new CrewsApi. 
    * @alias module:api/CrewsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the insertCrewCrewsPost operation.
     * @callback module:api/CrewsApi~insertCrewCrewsPostCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Insert Crew
     * @param {module:model/CrewRequestModel} crewRequestModel 
     * @param {module:api/CrewsApi~insertCrewCrewsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    insertCrewCrewsPost(crewRequestModel, callback) {
      let postBody = crewRequestModel;
      // verify the required parameter 'crewRequestModel' is set
      if (crewRequestModel === undefined || crewRequestModel === null) {
        throw new Error("Missing the required parameter 'crewRequestModel' when calling insertCrewCrewsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/crews/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
